language: python
python:
  - 3.7
  - 3.8
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install chainer
  - pip install Pillow
  - pip install pytest-cov
script:
  - pytest --cov-report=xml --cov=dl_framework tests/

after_success:
  - codecov

deploy:
  provider: pypi
  user: __token__
  password: $DL_FRAMEWORK_PYPI_TOKEN
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    branch: staging
